### PR TITLE
snacl: remove extra call to debug.FreeOSMemory

### PR DESCRIPTION
**Pull request by buck54321**

### CODE REVIEW

**Comment by jrick** [comment]
the comment pretty clearly explains the purpose of this, and you haven't provided any reason it is incorrect or doesn't matter today.

**Comment by buck54321** [comment]
The comment doesn't explain why it's being called twice in a row.

**Comment by chappjc** [comment]
I also figured the extra call was a mistake given the big comment appearing twice too.

**Comment by jrick** [comment]
ah, yeah good point. i didn't see the surrounding context or know it was being called twice in a row, comment included

tbh, i don't know how this got added. it's not part of btcwallet, and git blame doesn't point to any thing but the original decred commit.

It seems possible that it was added due to how finalizers work (https://godoc.org/runtime#SetFinalizer -- basically GC has to run twice to free anything with a set finalizer), but I don't recall for ceratin.

**Pull request merged**
