### PR TITLE
rpc: add unconfirmed to BalanceResponse message.

### PR DESCRIPTION
**Pull request by dnldd**

### CODE REVIEW

**Comment by dnldd** [comment]
@jrick will update this with the doc entry for the unconfirmed field once #918 has been merged.

**Comment by alexlyp** [comment]
Changes look ok, but you need to bump the minor version of the rpc.  so should be 4.22.0, 
and update docs as well.

**Comment by dnldd** [comment]
@alexlyp bumped the rpc minor version. Once #918 has been merged I'll update docs with the field entry.

**Comment by dnldd** [comment]
@alexlyp the docs entry for BalanceResponse's unconfirmed field has been done, PR should be good now.

**Comment by alexlyp** [comment]
Please bump the version number at the top of the docs as well.  And worth mentioning unconfirmed in relation to confirmation argument.  If min confirmation is 0 then unconfirmed will be 0, otherwise unconfirmed will be the balance that doesn't fulfill the requested min conf.

**Comment by dnldd** [comment]
@alexlyp PR updated.

**Comment by alexlyp** [comment]
@dnldd so you'll need to rebase this and bump the version again and regenerate the api.pb.go

**Comment by dnldd** [comment]
@alexlyp PR should be good now.

**Pull request merged**
