### PR TITLE
Move log setup to before first use of logger

### LINKED ISSUE #630: Wallet cannot warn about missing config file
Warning is done before logging is set up.  Should be the final check (as it is in dcrd).

### PR DESCRIPTION
**Pull request by jcvernaleo**
This allows warning to be shown since it is now after the logger is
setup and it matches what the comment says about going last.

Closes #630

### CODE REVIEW

**Comment by jrick** [comment]
Does this actually fix some observable bug?  Going by the comment, i think it might already be in the correct location, at least if we are only talking about actually parsing and not validating config options.

**Comment by jcvernaleo** [comment]
The thing is, it cannot actually write to the log where it is.  I saw that when I initially put the testnet old dir check right above it.  No logger is setup at the point where it is despite it trying to use log.Warn

**Comment by jcvernaleo** [comment]
If you want it higher up that is fine, but it has to go after https://github.com/decred/dcrwallet/blob/5846785e0cec13df9642ca23ef53b745d767bbde/config.go#L600 at the very least instead of at 
https://github.com/decred/dcrwallet/blob/5846785e0cec13df9642ca23ef53b745d767bbde/config.go#L458
where it currently is.

**Comment by jrick** [comment]
That works, or we could initialize logging sooner.  Ideally i think logging should be initialized as soon as possible.

**Comment by jcvernaleo** [comment]
Up to you between this move and moving the logging.  I can go either way.  Moving the logging is probably more work though :)

**Comment by jrick** [comment]
Let's try to move the logging up instead, i don't like how this warning will no longer be printed if there is another config validation error (because of bad input on the command line) since this function will have returned early.

**Comment by jcvernaleo** [comment]
Moved it back and move the log setup earlier.

If this is good, I will change the name of the PR to better reflect what was done of course.

**Comment by jrick** [comment]
This look good

**Pull request merged**
