### PR TITLE
Jcv grpcdoc

### PR DESCRIPTION
**Pull request by jcvernaleo**

### CODE REVIEW

**Comment by jrick** [comment]
This looks reasonable but the Paymetheus decred port will need to be updated at the same time.

**Comment by alexlyp** [comment]
ACK, make sure you also reference that this fixes #76 as well.

**Comment by jcvernaleo** [comment]
@alexlyp It should reference the issue in the commit message.

**Comment by jcvernaleo** [comment]
@jrick would you prefer I leave the api calls as StartBtcdRpc instead or do a PR on Paymetheus?  Another option would be to make it StartDaemonRpc in both of them.

**Comment by jrick** [comment]
Naming the RPCs the same for each program is better when possible.  StartDaemonRpc would be ok, but I think I like StartConsensusRpc better.

**Comment by jcvernaleo** [comment]
I like StartConsensusRpc better too (didn't think of that).  I'll update this PR with that then PR the upstream ones too.

**Comment by jrick** [comment]
I think it makes more sense to leave it unchanged here, change it in btcwallet, and pick it up during sync.

**Comment by jcvernaleo** [comment]
@jrick there you go (and squashed).

**Comment by jrick** [comment]
ok

**Comment by jcvernaleo** [comment]
@jrick I've sort of struggled on how to phrase the legacy rpc server stuff.  It is based on btcd's legacy server more than bitcoin-core's but even then it breaks compatibility in ways that btcd wouldn't since it is very much not a bitcoin rpc server.  So either way seems kind of wrong to me.

**Comment by jrick** [comment]
Perhaps just "A legacy JSON-RPC server is also available..."?

**Comment by jcvernaleo** [comment]
That would work.

**Pull request merged**
