### PR TITLE
Introduce --enableticketbuyer option to turn on purchaser.

### LINKED ISSUE #464: Newly added ticketbuyer should be require to be opted-in
Because the newly added ticketbuyer functionality is distinctly different than existing dcrwallet auto ticket purchasing, we should require users to opt-in via a commandline option (--ticketbuyer)  for that functionality to be exposed.  That along with clear documentation about what the default values are and how each param will effect ticket purchasing would be the best.

### PR DESCRIPTION
**Pull request by jrick**
This feature can not be used with the old --enablestakemining feature.

Fixes #464.

### CODE REVIEW

**Comment by jolan** [comment]
Well this turns off voting when ticketbuyer is on (handleWinningTickets will never run).

**Comment by jrick** [comment]
oh, good catch. I don't know what to do about that.

Wish we would have just dumped the old buyer.

**Comment by jolan** [comment]
Maybe BuyingAlgorithm={wallet,ticketbuyer}?  And I agree, the built-in code isn't useful for most people anymore.

**Comment by jrick** [comment]
Discussed with @alexlyp and will open a new issue+PR for the changes we've decided on.

**Pull request closed without merging**
