### PR TITLE
Fix all rpclisten references in documentation

### PR DESCRIPTION
**Pull request by jyap808**
Fixes issue https://github.com/decred/dcrwallet/issues/99

### CODE REVIEW

**Comment by davecgh** [comment]
Nice.  Thanks for the PR.  Looks correct to me.

OK

**Comment by cjepson** [comment]
utACK looks good

**Comment by alexlyp** [comment]
looks good, but can you rebase to current master?  then it can go right in

**Comment by jyap808** [comment]
It looks like this commit can merge cleanly?

**Comment by davecgh** [comment]
It is much preferred to keep a clean history that is not cluttered up with useless merge commits.  There are definitely times where merge commits make sense such as when syncing upstream, but for normal additions like this, they really don't make any sense.

**Comment by jyap808** [comment]
OK done. Hope I did it right.

I also modified the commit message slightly. Changed "rpcport" to "rpclisten". Cheers.

**Comment by alexlyp** [comment]
great looks good, thanks for doing that!

**Pull request merged**
