### PR TITLE
Modify the logic for password prompting

### PR DESCRIPTION
**Pull request by cjepson**
Password prompting on first run or when --promptpass has been
set now prompts before the RPC server has started. If the wrong
password is entered, the user is reprompted to enter their
password.

### CODE REVIEW

**Comment by alexlyp** [comment]
tACK works for me

**Comment by jcvernaleo** [comment]
Yep, works in my testing too.
tACK

**Comment by jrick** [comment]
huge OK on this change.  all prompting should be done from the main package.

**Comment by chappjc** [comment]
`promptPass || w.StakeMiningEnabled`

Seems to prevent scripted launch of staking wallet, followed by manual unlock via RPC. The new procedure will require unlock with the private passphrase at wallet startup instead.  Is that correct?

**Comment by cjepson** [comment]
Yes. I haven't been sure about this one, @davecgh suggested making this change but it might make it hard for fallback scripts to operate. I think this maybe should be removed.

**Comment by cjepson** [comment]
@chappjc Okay, I have removed the auto-prompt for enablestakemining flag. Ready to merge.

**Comment by jcvernaleo** [comment]
Cool, looks good for me still too.  Going in.

**Pull request merged**
