### PR TITLE
walletrpc doc fix+go.mod addition

### PR DESCRIPTION
**Pull request by peterzen**
- Updated client usage doc to point to correct package path
- Added `go.mod` to facilitate local client development using `replace`

### CODE REVIEW

**Comment by jrick** [comment]
Remove the go.mod/sum, we are not adding submodules to dcrwallet.

**Comment by peterzen** [comment]
What is the proper way to develop locally against master `rpc/walletrpc`, e.g. getting around 

```
$ go build
go: decred.org/dcrwallet/rpc/walletrpc@v0.3.0: parsing go.mod:
	module declares its path as: github.com/decred/dcrwallet/rpc/walletrpc
	        but was required as: decred.org/dcrwallet/rpc/walletrpc
```

**Comment by jrick** [comment]
replace the decred.org/dcrwallet module with your development version

**Comment by peterzen** [comment]
I work on client code that needs `decred.org/dcrwallet/rpc/walletrpc@master` - isn't `go get decred.org/dcrwallet/rpc/walletrpc@master` supposed to suffice?

**Comment by jrick** [comment]
no, because some historic tags exist.  Instead, do `go get decred.org/dcrwallet@master` after removing the other existing dcrwallet module requires from your project.  we used to have submodules everywhere, and they were removed in ae5a0c6ffb13bd1383968e1bb8cf4abe66c59f87.

**Comment by peterzen** [comment]
Cool, thanks!

**Pull request merged**
