### PR TITLE
Make dcrwallet pass all goclean.sh tests.

### PR DESCRIPTION
**Pull request by jcvernaleo**
I didn't squash this yet in case any specific changes need looking at.

### CODE REVIEW

**Comment by jcvernaleo** [comment]
@cjepson In particular, could you look at 38187f006cee8bb74549ce9b09757e0bbd61da91 ?  Most of the others are comments or unkeyed fields but this one go vet found some code that was doing something kind of weird.

**Comment by jcvernaleo** [comment]
Also worth noting that this does NOT run go test on the repo since there are still a few broken unit tests.

**Comment by alexlyp** [comment]
looks good now.  squash and should be good to go

tACK

**Comment by cjepson** [comment]
tACK

**Pull request merged**
