### PR TITLE
Always sync database addresses when persisting returned index.

### LINKED ISSUE #1333: Wallet does not see addresses nor transactions
When I create new addresses with `getnewaddress` RPC call, then immediately try to `dumpprivkey`, I get in the response:
```
"error": {
        "code": -4,
        "message": "address not found"
    },
```

However, `validateaddress` show it works, with the response:
```
"result": {
        "isvalid": true,
        "address": "Ssa3tyzqMTYFEGc14SuSeSUhDmFiv5HHv5z"
    },
```

I also don't see transactions to addresses created with `getnewaddress`. Calls to `listtransactions` will show outgoing transactions to those addresses if I send coins to them, but not the incoming ones. Doesn't `getnewaddress` add the address to the wallet?

I am creating new addresses with the gappolicy ignore. I'm also trying to generate many spare addresses, like 1000. I also tried experimenting with `dcrwallet.conf` values:
```
gaplimit=10000
addridxscanlen=10000
```

But no luck. Any ideas? This is very different from other bitcoin-like currencies that maintain the private keys.

### PR DESCRIPTION
**Pull request by jrick**
This fixes lookup errors or missing details of addresses returned by
getnewaddress and account branch extensions performed by
accountsyncaddressindex.

Fixes #1333.

### CODE REVIEW

**Comment by jrick** [comment]
@jseibel-circle please test this.  You may need to derive one additional address in the branch before any of them are available again, but on a fresh wallet everything should always be accessible.

**Comment by jseibel-circle** [comment]
I will test this, will need several hours

**Comment by davecgh** [comment]
For reference, I opened #1335 for the separate in-memory branch index issue.

**Comment by jseibel-circle** [comment]
I've verified that the wallet properly tracks addresses created with `getnewaddress` when compiling this version from source. THANKS!!!

**Pull request merged**
