### PR TITLE
legacyrpc: mark expired tickets as such

### PR DESCRIPTION
**Pull request by jolan**
Closes #716.

### CODE REVIEW

**Comment by jrick** [comment]
What happens when it hasn't been spent?

**Comment by jolan** [comment]
They always have heightspent set:

https://github.com/decred/dcrwallet/blob/7c4f9160d1cbd5faee29b1c52ac9e1aec11e9607/wallet/chainntfns.go#L567-L577

**Comment by chappjc** [comment]
But that's only handling when a revoke comes in, no?  What if the stakepool wallet hasn't sent the revoke?

**Comment by jolan** [comment]
That is the only place the status is updated to missed.

**Comment by jrick** [comment]
So this change appears to be correct in the sense that it produces the right results but that is only because the code that first inserts the ticket does so with a "spent height" of the block it is contained in.  This is obviously wrong (the spent height should be some sentinel value like -1 if it hasn't been spent) but without doing a db upgrade i don't see any previously inserted tickets could be fixed.

This code also only matters when running in stakepool mode, so if the results are correct and make stakepools happy, i'm alright with this going in.

**Comment by jolan** [comment]
Thanks.  Maybe I should have prefixed this by saying the underlying implementation is wonky.

**Pull request merged**
