### PR TITLE
Tidy up creation of VSP clients.

### PR DESCRIPTION
**Pull request by jholdstock**
Removing a lot of duplication and boilerplate. Will squash before merge.

### CODE REVIEW

**Comment by jrick** [comment]
the second commit changes the error code for invalid vsp arguments from InvalidArgument to Unknown. intentional?

**Comment by jholdstock** [comment]
Good catch, not intentional. I'll need to rethink this.

**Comment by jholdstock** [comment]
Marking this PR as draft because it has significant overlap with #2428

**Comment by jholdstock** [comment]
Rebased on master and ready to review again.

With the changes from #2428, the only errors returned from `wallet.VSP` are caused by invalid arguments, so I've changed the error code per the observation from @jrick.

**Review by jrick — APPROVED** [review]

**Pull request merged**
