### PR TITLE
Merge branch 'upstream'

### PR DESCRIPTION
**Pull request by jrick**
This syncs up through btcwallet commit 620a3c649e31c051cbc6b84ae75f840129db21be.

### CODE REVIEW

**Comment by jcvernaleo** [comment]
I've been running with this branch on three nodes all weekend.  Other than seeing this error on one node a bunch at first (haven't seen it since Friday though):
dcrwallet.log.4:16:58:49 2016-02-26 [ERR] WLLT: Notifying unmined tx notification while creating notification for blocks
everything seems to be running well.

**Comment by jrick** [comment]
That's a bug in btcwallet, I've seen it there too.  It should only affect users of the new gRPC notification streams since that's the only place where the wallet's notification server is hooked up to.  It may even be harmless (the code continues operating as if there was no error, except for logging it) but it does mean that some invariants weren't being upheld like I originally thought.

**Comment by alexlyp** [comment]
tACK, ran 2 TN nodes all weekend.  Both successfully voted and bought tickets as expected.

**Comment by cjepson** [comment]
tACK on sim

**Comment by jrick** [comment]
Updated merge commit with the correct parents.

**Comment by jcvernaleo** [comment]
OK

**Pull request merged**
