### PR TITLE
multi: Deprecate Consolidate RPC.

### PR DESCRIPTION
**Pull request by dnldd**

### CODE REVIEW

**Comment by chappjc** [comment]
What is the motivation for deprecating consolidate, and what is proposed to replace it?

**Comment by dnldd** [comment]
The primary use case for `Consolidate` is sweeping all eligible prevOuts from an account. The RPC currently expects an input count to consolidate as a parameter. This parameter isn't necessary, the provided source account can be searched for all eligible prevOuts by specifying the number required confirmations an output must have to be eligible. 

[`SweepAccounts`](https://github.com/decred/dcrwallet/pull/1098)  is to replace `Consolidate`.

**Comment by jrick** [comment]
one thing we need to do to sweep before we can deprecate consolidate is to check for a maximum transaction size and reduce the number of inputs if the transaction would be too large.  consolidate is currently useful for e.g. exchanges who want to clean up dusty wallets as it allows them to specify the number of inputs to use which isn't a perfect means, but does allow them to avoid creating transactions too large.

Otherwise, sweepaccount could likewise gain an optional field to specify the maximum number of inputs to use.

**Comment by chappjc** [comment]
The reasons I find consolidate indispensable are:
1. specifying number of inputs to use
2. specifying output address

Doing away with 1. without a replacement is not a good idea IMO.

**Comment by jrick** [comment]
Exchanges use consolidate as well for the same reason (specifying number of inputs) so after further thought it's probably best to leave this alone.  The implementation can be cleaned up without changing the external API.

**Pull request closed without merging**
