### PR TITLE
rpc: Add blockheight to getstakeinfo results

### LINKED ISSUE #213: show block height with getstakeinfo
It would be useful for the 'getstakeinfo' output to also show the block height. A lot of the data it returns is referring to information that is tied to the block height, and the data set is less useful if it is not known what block height it is referencing. 'getblockcount' could be called separately, but that could introduce data errors due to the race condition.

### PR DESCRIPTION
**Pull request by alexlyp**
Needs dcrd commit b58d1c4bd45c3fce89318ada51dd1288b5c5c58d
Fixes #213

### CODE REVIEW

**Comment by jrick** [comment]
Isn't this also missing the help description?

**Comment by alexlyp** [comment]
thanks. added to help

**Comment by jcvernaleo** [comment]
Fails to build with: 
```
jcv@triforce dcrwallet $ go install
# github.com/decred/dcrwallet/rpc/legacyrpc
rpc/legacyrpc/methods.go:1442: unknown dcrjson.GetStakeInfoResult field 'BlockHeight' in struct literal
```
which I think is also what travis is complaining about.

**Comment by jcvernaleo** [comment]
That's what I get for looking at PRs in the wrong order.  Will look at this again when decred/dcrd#274 goes in.

**Comment by jcvernaleo** [comment]
Looks good and works when I test it.
tACK

**Pull request merged**
