### PR TITLE
Check an unchecked error

### PR DESCRIPTION
**Pull request by jrick**
Credit to @jholdstock for spotting this a couple days ago

### CODE REVIEW

**Comment by jholdstock** [comment]
What about the case where `err != nil` and  `err != errors.Locked`, inside `vspClient.SetVoteChoice`?

https://github.com/decred/dcrwallet/blob/9a8688e60b08b68b5952bb717122669cbb3e0989/internal/vsp/vsp.go#L337-L343

**Comment by jrick** [comment]
Maybe that error could be handled better but it's not returning nil for no reason.  We are intentionally not doing anything for the ticket if it is not submitted to that particular vsp.

**Comment by jholdstock** [comment]
I've just spotted that the same err is also unchecked in the grpc version of the call

https://github.com/decred/dcrwallet/blob/9a8688e60b08b68b5952bb717122669cbb3e0989/internal/rpc/rpcserver/server.go#L4061-L4071

**Comment by jrick** [comment]
merged as part of #2134

**Pull request closed without merging**
