### PR TITLE
multi: add wallet sendrawtransaction command

### LINKED ISSUE #1268: sendrawtransaction JSON-RPC is unusable with --spv
It's trying to perform RPC passthrough:

```
-9: RPC passthrough requires dcrd RPC synchronization
```

### PR DESCRIPTION
**Pull request by kLkA**
closes #1268

this change adds sendrawtransaction wallet command for use in spv mode
as there is no connection to RPC consensus server

### CODE REVIEW

**Comment by jrick** [comment]
I haven't tried running this yet but I suspect that this change doesn't work.  PublishTransaction works a bit differently for p2p protocol.  Rather than pushing a transaction message to peers, it sends an inventory message announcing the availability of the transaction.  If (and only if) the remote peers do not have the transaction yet should they then request the transaction with a getdata message.  In the SPV Syncer implementation, when a getdata for a transaction is received, the transaction is then looked up through the wallet, but in this particular case the transaction won't be found (this RPC handler did not save the transaction to the wallet and other peers will not be able to query for it).

Saving the transaction to the wallet is not necessarily the correct option here either, because the transaction may not be relevant to this wallet.  It won't screw up balances, but you will begin to see the transaction in output of listtransactions (for example).

Some more thought needs to be put into this to decide how and where to save the transaction for peer query.

**Comment by kLkA** [comment]
@jrick from your words I understood that `sendrawtransaction` dcrd command can insert any tx so it will later be accepted and mined/validated if so. Also as you say currently creation of TXs on behalf of wallet consist of two things: creation of tx with saving to walletdb and publish inv message to p2p network so others can grab it. 
1) Am I right that dcrd will grab it with `getdata` func (yet not found this code)
2) Maybe we can allow SPV wallet to save + publish tx if it's only related to this wallet? So it will be a new rule that SPV wallet can `sendrawtransaction` only for it's own transactions?

**Comment by jrick** [comment]
1. Yes, [here](https://github.com/decred/dcrd/blob/47ade78c1a4e350313e9b5d9f5556f707ad22d0d/blockmanager.go#L1346-L1355) is the dcrd code which handles the inv message and [here](https://github.com/decred/dcrwallet/blob/13e866b50a229ed03abfb53a739208e14664d93a/spv/sync.go#L511-L537) is how the spv syncer handles the getdata for the transaction.
2. If the transaction is relevant to the wallet, it is fine to save it to the database, but if it's not I don't feel that we should save it (others are fine to chime in though if you have a use case for saving a transaction that isn't relevant. perhaps it will be later?).  Another alternative would be to keep the transaction in memory, managed by the spv syncer itself, so it is able to serve the transaction directly rather than making a wallet DB query.

**Comment by chappjc** [comment]
Superseded by https://github.com/decred/dcrwallet/pull/1846, I believe

**Comment by jrick** [comment]
Correct.

**Pull request closed without merging**
