### PR TITLE
Output of --help/-h should go to os.Stdout rather than os.Stderr

### PR DESCRIPTION
**Pull request by chappjc**
Similar to dcrd PR https://github.com/decred/dcrd/pull/386

### CODE REVIEW

**Comment by marcopeereboom** [comment]
I am an old UNIX guy and I believe it should go to stderr and exit with an error.  That would be the least surprising thing in a script.  Also, I don't believe that cli help is a substitute for a man page.  Therefore, I vote we don't accept this PR.

That said, I am open to other opinions and I want this voted on by others.

**Comment by jrick** [comment]
I am in favor of printing help to stdout when it was explicitly asked for, and returning 0 back to the OS.  If the help is printed in response to an unknown flag or config file option, then it should print the help to stderr and return with a nonzero exit code.

**Comment by jcvernaleo** [comment]
I agree with @jrick (and the PR) and think -h should go to stdout.

**Comment by jrick** [comment]
My only issue with this PR is that it will print help to stdout in all cases, even when an unknown flag is seen.  It also returns 1 back to the OS when help is printed with -h (and I think it should return 0, because it printed help successfully).

**Comment by chappjc** [comment]
To me this is not a *nix expectation.  No matter the OS, I expect to be able to pipe the output of a help message that I explicitly requested into a pager without redirecting stderr to stdout.

But I'm not sure this PR is done right.  It's different from dcrd (https://github.com/decred/dcrd/pull/386) where the check is like this:

```go
if e, ok := err.(*flags.Error); ok && e.Type == flags.ErrHelp {
	fmt.Fprintln(os.Stdout, err)
	return nil, nil, err
}
```

This is saying that the `-h` switch was passed, but that's not what _this_ PR did.  For dcrwallet here, it might need this:

```
if e, ok := err.(*flags.Error); !ok || e.Type != flags.ErrHelp {
	preParser.WriteHelp(os.Stderr)
} else if e.Type == flags.ErrHelp {
	preParser.WriteHelp(os.Stdout)
	os.Exit(0)
	// or loadConfigError(nil)
}
```

or whatever passes for idiomatic Go in this case.

**Comment by chappjc** [comment]
I've updated https://github.com/decred/dcrd/pull/386 as per this discussion.  But this dcrwallet PR needs a resolution.

**Comment by jrick** [comment]
We are busy with prepping the next release right now so this will be looked at for 0.6.

**Comment by marcopeereboom** [comment]
Will NOT be looked at for 0.6.0

**Comment by chappjc** [comment]
Dunno how this should be.  Two things that make this different from the dcrd change:

1. There's a `preParser` and a `parser`.  First comes `preParser.Parse()`, and the check for `ErrHelp`.  So IMO there's no point to extra logic for `parser` later in `loadConfig`.
2. Most errors in `loadConfig` are handled by returning a `loadConfigError(err)`, and this propagates up to `walletMain` and `main`, where any non-nil error gets a `os.Exit(1)` there.  There are some os.Exit calls in loadConfig, and I don't see a clear pattern to when loadConfigError is used vs os.Exit.

**Comment by alexlyp** [comment]
@chappjc, yah after looking at code, not quite sure on how to handle due to the differences.  I'll discuss with @jrick and we'll give you an update.  At any rate, this will be in 0.6.0

**Comment by alexlyp** [comment]
So we still think this isn't quite doing what we'd like.  

Decribed by @jrick: 
> I am in favor of printing help to stdout when it was explicitly asked for, and returning 0 back to the OS. If the help is printed in response to an unknown flag or config file option, then it should print the help to stderr and return with a nonzero exit code. 

Do you want us to knock this one out?

**Comment by chappjc** [comment]
Go for it.  :)

**Pull request closed without merging**
