### PR TITLE
Fix panic when getting StakeDifficulty if dcrd disconnected

### PR DESCRIPTION
**Pull request by cjepson**
Calling wallet.StakeDifficulty or wallet.StakeInfo would cause a panic if the daemon was not connected to the wallet. Now the chain client is loaded by the disconnection-safe w.requireChainClient.

### CODE REVIEW

**Comment by alexlyp** [comment]
utACK

**Comment by jrick** [comment]
ok

**Comment by marcopeereboom** [comment]
ok

**Comment by alexlyp** [comment]
ok on the updates as well

**Comment by jrick** [comment]
ok again

**Pull request merged**
