### PR TITLE
Add golang 1.7 and drop golang 1.5 support.

### PR DESCRIPTION
**Pull request by dajohi**

### CODE REVIEW

**Comment by jrick** [comment]
ok

**Comment by dajohi** [comment]
Updated

**Comment by jrick** [comment]
update the commit description to "add 1.7 support, drop 1.5" or something along those lines, since this does more than just update the travis config now.

**Comment by dajohi** [comment]
Done

**Comment by jrick** [comment]
ok

**Comment by alexlyp** [comment]
OK

**Comment by marcopeereboom** [comment]
ok

**Pull request merged**
