### PR TITLE
Improve wording and fix word order.

### PR DESCRIPTION
**Pull request by frankbraun**

### CODE REVIEW

**Comment by davecgh** [comment]
I agree with the word order fix regard `to a`, but it does both authenticate to dcrd's RPC server and *also* sets the user/pass for dcrwallet's RPC server.

It might be worth explaining that point a little better since I don't think it's super obvious from that comment.

**Comment by jcvernaleo** [comment]
@frankbraun I agree with @davecgh here.  The word order fix is correct by 'authenticate' is more accurate than 'connect' unless you want to expand on the comment a bit as he suggested.

**Comment by frankbraun** [comment]
Thanks for the input @davecgh and @jcvernaleo. I changed the commit accordingly. I hope it is clearer now.

**Comment by davecgh** [comment]
:+1:

**Comment by jcvernaleo** [comment]
Great, going in.  Thanks!

**Pull request merged**
