### PR TITLE
Update addrmgr module

### PR DESCRIPTION
**Pull request by jrick**
This provides performance improvements under SPV mode when few quality peers are available to return.

### CODE REVIEW

**Review by chappjc — APPROVED** [review]
LGTM, although in dex we're still gonna be using the pseudo version at v2.0.10-0.20230206141716-f9452d346121`
Worth making a backport and proper `v2.0.10` tag?

**Review by davecgh — APPROVED** [review]

**Comment by jrick** [comment]
@chappjc you control the deps there so any wallet requires can be pushed ahead.

**Comment by chappjc** [comment]
I was partly alluding to the deadlock fix in the wallet code

**Comment by jrick** [comment]
Ah, understood. Sure we can do that.

Only fair to give you a proper wallet tag now, since I waited in wallet for the addrmgr tag before updating :)

**Pull request merged**
