### PR TITLE
Add controlled startup RPCs to the gRPC interface.

### LINKED ISSUE #385: gRPC interface needs method to resync accounts/addresses using BIP0044 address discovery
This is the final required component to make seed restoring possible over gRPC.

### LINKED ISSUE #389: Add more controlled startup RPCs
We want the following features (RPCs) available in the gRPC interface:

- [ ] BIP0044 account discovery (tracking in #385)
- [ ] Subscribe the wallet to the block notifications
- [ ] Fetch missing headers
- [ ] Load the consensus RPC server's client tx filter with all active wallet data for relevant tx notifications
- [x] Rescan previously unseen blocks before fetching headers (already implemented by #382)

These RPCs are desired as they provide the client with the ability to know precisely what startup action the wallet is performing.  A downside is that now clients must know the correct order to call these (the order above), and remember to call them, or the wallet may not work as expected.  However, for clients that do not care about startup actions, the wallet can be opened without `--noinitialload` (the default behavior) which will cause the dcrwallet main package to open the wallet on behalf of any clients.

In order for any of the above to be useful, the automatic synchronization done by the gRPC LoaderService when both the wallet and RPC client are created must also be removed.

### PR DESCRIPTION
**Pull request by jrick**
This allows the client to orchestrate the bringup and syncing of the
wallet with the consensus RPC server.  This does add complexity to the
client, but the tradeoff is the client is well aware of what the
wallet is doing and can present more detailed information to the user.
This can improve the user experience.

This change also adds the RPC for BIP0044 address (and optional
account) discovery.  Account discovery is one of the new features this
API provides, and is required for clients to perform seed restoring.

Closes #385.

Closes #389.

### CODE REVIEW

**Comment by jrick** [comment]
This is a breaking change and will require changes to Paymetheus before it is ready to be merged.  It is ready for code review.

**Comment by jrick** [comment]
Paymetheus PR is open and both of these are ready to be merged, after review.

Travis is failing for an unrelated issue.

**Comment by alexlyp** [comment]
Changes look good, tACK on existing wallet systems, but can't speak to the changes that will effect Paymetheus, when someone tACKs that stuff I will approve for merge

**Comment by jrick** [comment]
Accidentally forced push a branch from the wrong repo, with the same branch name.  GH won't let me reopen.  Making a new PR.

**Pull request closed without merging**
