### PR TITLE
Add address argument to consolidate.

### PR DESCRIPTION
**Pull request by chappjc**
Add an address argument to Wallet.compressWallet() and the consolidate legacy RPC.  This PR requires https://github.com/decred/dcrd/pull/317

Tested on testnet with default arguments, and with all 3 arguments using an address from a different account in the same wallet, and again with an address from the sending account (not that it should matter).

### CODE REVIEW

**Comment by chappjc** [comment]
Tested on testnet.  Works with and without an address.  Confirmed that the input address is used.

Also confirmed it rejects invalid addresses.  e.g. on testnet:

    -5: Invalid address "Ds...": decode failed with `unknown address type`

Suppose I'll try on mainnet, unless anyone wants to raise a red flag.

**Comment by alexlyp** [comment]
OK looks good along with drcd PR

**Comment by chappjc** [comment]
Tested on mainnet with address from another wallet.

**Comment by cjepson** [comment]
OK

**Comment by cjepson** [comment]
OK

**Comment by alexlyp** [comment]
So this will be merged along with dcrd PR, when dcrd PR 284 is merged.

**Comment by alexlyp** [comment]
Can you rebase this please?  Want to confirm it's good to go with updated dcrd versions in glide.

**Comment by chappjc** [comment]
Rebased, but need to retest b/c of resolved conflict, and the deps.

**Comment by alexlyp** [comment]
Just tested along with @dajohi fix for consolidate.  Looks good to me:
https://testnet.decred.org/tx/6ad64140ecc289f2415915ea9a8538148bfb8ec0e8f71a3b48acea8ad35168c1

with consolidate 300 default TsYsLcGrFroBCWSw48kaMHa2xx5Exporg9j

**Comment by chappjc** [comment]
Cool.  I can't really test this on mainnet until later, so that's good.

**Pull request merged**
