### PR TITLE
Move prompting of passphrases and seed to prompt pkg.

### PR DESCRIPTION
**Pull request by jrick**
This will allow other tools to call the same prompts, passing these
arguments to either the wallet.Create function or to the wallet.Loader
type to create a new wallet.

### CODE REVIEW

**Comment by alexlyp** [comment]
tACK

**Comment by alexlyp** [comment]
tACK, creating wallet as normal and unlocking wallet via prompt still work as expect

**Comment by marcopeereboom** [comment]
Looks good.  Please get this in.

**Comment by cjepson** [comment]
utACK

**Pull request merged**
