### PR TITLE
Bump for v1.0.0

### PR DESCRIPTION
**Pull request by jcvernaleo**

### CODE REVIEW

**Comment by jrick** [comment]
still beta?

**Comment by jcvernaleo** [comment]
I really don't know what we want to do there.  Google kind of messed this up for everyone by making the 'beta' label meaningless to most people.

So if anyone has a strong opinion either way I'll support it.

**Comment by jrick** [comment]
I think it should be dropped, and in dcrd too.

**Comment by jcvernaleo** [comment]
After discussion on zkc we've agreed to remove the 'beta' label.

**Pull request merged**
