### PR TITLE
Change default relay fees

### PR DESCRIPTION
**Pull request by cjepson**

### CODE REVIEW

**Comment by alexlyp** [comment]
OK

**Comment by jcvernaleo** [comment]
Looks good to me (and even matching comments!)
OK

**Comment by kargakis** [comment]
It would be nice if I had an option to have my fee set dynamically based on the average fee in the memory pool at the time of the tx (without having to script it out).

**Comment by chappjc** [comment]
@kargakis @cjepson Built that functionality into dcrticketbuyer.  https://github.com/cjepson/dcrticketbuyer

**Comment by kargakis** [comment]
@chappjc @cjepson cool! I had a look at it and feesource=mean seems to be what I am asking for.Can't wait to see it in the decred suite.

**Comment by raedah** [comment]
fix spelling so it says 'transaction' instead of 'transation'

**Pull request merged**
