### PR TITLE
Also promptpass when enablevoting

### LINKED ISSUE #732: wallet unlock for enablevoting
We prompt the user to unlock the wallet is they are using enableticketbuyer, but we dont prompt the user to unlock the wallet if they are using enablevoting. Both equally require the wallet to be unlocked in order to function, so the expected behavior is for the unlock prompt behavior to be the same.

### PR DESCRIPTION
**Pull request by alexlyp**
Fixes #732

### CODE REVIEW

**Comment by jrick** [comment]
Don't like this, see discussion in #732

**Comment by alexlyp** [comment]
Well you suggested to 'go the other way' but removing all prompting when users enable options that require unlocking seems like a bad solution.

**Comment by alexlyp** [comment]
I feel that the use of these 2 options requires permanently unlocked wallets.  And therefore a prompt seems acceptable.

**Comment by jrick** [comment]
Prompting from a daemon is a bad solution too.  Daemons are not supposed to be interactive.  What has to happen is these features aren't enabled until unlocked.

**Comment by alexlyp** [comment]
ok agreed. i'll remove both checks then

**Comment by jrick** [comment]
The one for ticketbuyer unfortunately needs to be left in at this time, it can't be started at all until the passphrase is available without some major refactoring.

That's why nothing has been done here yet, it's serious work.

**Pull request closed without merging**
