### PR TITLE
Add consolidate command handling to the wallet JSON RPC

### PR DESCRIPTION
**Pull request by cjepson**
This adds consolidate command handling to the JSON RPC. The command takes
an integer representing the number of inputs you would like to compress
and then produces a transaction compressing them. The transaction hash
is returned in response.

### CODE REVIEW

**Comment by alexlyp** [comment]
tACK.  

Testing on simnet with dcrctl --wallet listunspent | wc -l,  appears to show a reduction of 11 lines (the number of lines in 1 jsonresult of a utxo in that list) every time you dcrctl --wallet consolidate 1

Also 
 [INF] WLLT: Successfully consolidated funds in transaction 68ba49fdbd5fe050522dd182d513ffb7b71dc297379d30e4db4c1b4756e4f3a9

dcrctl getrawtransaction 68ba49fdbd5fe050522dd182d513ffb7b71dc297379d30e4db4c1b4756e4f3a9 

shows 10 vins, and 1 vout

**Comment by jcvernaleo** [comment]
OK once decred/dcrd#59 gets in

**Comment by cjepson** [comment]
On hold for the sync branch so jrick doesn't kill me.

**Comment by cjepson** [comment]
Rebased

**Comment by jrick** [comment]
OK on the added RPC.  I have not reviewed the internal compressWallet func that this is calling, but this change by itself looks ok.

**Comment by jcvernaleo** [comment]
I believe this is missing the help text.

**Comment by jcvernaleo** [comment]
Other than the help tACK

**Comment by jcvernaleo** [comment]
OK

**Comment by chappjc** [comment]
I must be doing something wrong, I either get:

`-22: TX rejected: transaction output has negative value of -5000000`

if I use consolidate 1, or 

`-22: TX rejected: tried to spend zero value output from input <hash>, idx 2`

if I use consolidate N, for N>1.

I'm trying to consolidate because I can't purchase a ticket despite having many times the required amount.  I'm not using reuseaddress or ticketaddress, so why are my funds not able to create a SSTX?

**Comment by cjepson** [comment]
It's a consolidate specific bug, it's patched on my PR branch #104 indirectly

**Pull request merged**
