### PR TITLE
RFP-10 Milestone 1

### PR DESCRIPTION
**Pull request by chappjc**
This PR should be ready to go now.  However, the multi-harness system needs some optimization in upcoming tests. <s>This PR needs review, from myself and upstream developers.</s>

Included in this PR are the test functions listed under milestone 1 of RFP-10, refactoring of rpctestharness, and updates to test functions for future milestones.  The **milestone 1 tests** include:

- [x]  getnewaddress
- [x]  validateaddress
- [x]  walletpassphrase
- [x]  getbalance
- [x]  listaccounts
- [x]  listunspent

Tests for milestones 2 and 3 (completion _not required_ for this PR) include:
- [x]  sendtoaddfress (m2)
- [x]  sendfrom (m2)
- [x]  purchaseticket (m3), done for this PR, but needs work

A summary of TODOs (mainly questions) from commit messages in this PR:

- Consider additional harnesses to avoid multiple leftover accounts, and potentially unmined tx.
- <s>In dcrrpcclient, fix documentation bug for ListUnspent, as it specifies the wrong value for max conf (999999 vs. 9999999).</s> https://github.com/decred/dcrrpcclient/pull/32
- <s>What is with the 10 second (now 2 second) delay in testSendFrom?</s>
- Comments and docs, better multi-harness system, P2SH type validateaddress test (IsScript func).
- <s>For testWalletPassphrase
  - Test that a restricted operation fails/passes?</s>
  - Test WoW unlock error?  Maybe in the future, as this requires some harness rework.
- For testGetBalance:
  - <s>Mine a block and check anything</s>
  - I think there is a bug in Store.balanceFullScan() in tx.go, where the check is minConf == 0 instead of minConf < 1.  This allows minconf=-1 to pass but the unconfirmed transaction output handling section of balanceFullScan does not execute.
- <s>Expand testListAccounts for minconf=1 since this is very different computation, although we're really testing the RPC interface rather than the underlying computations.</s>
- <s>Add a ListAccounts test before and after create an account?</s>

### CODE REVIEW

**Comment by alexlyp** [comment]
Looking really good so far.

I'm on board with any restructuring of the test harnesses that you feel is necessary and would help speed up testing.  

Couple things:

- Make sure to remove all the t.Log()
- Yah not sure how createaccount wasn't added here, but that should be tested in conjunction with listaccounts like you suggested.
- Yes, please test those other paths for testWalletPassphrase (ie trying to send while not unlocked etc)
- Interesting, if you think you may be correct about the balanceFullScan issue.  I'll look into that more closely.
- The delay added in testSendFrom was due to inconsistent results I was seeing.  Basically, sometimes wallet wouldn't be "caught up" and then the expected balance would not match the observed balance.  It has to do with wallet's slow block processing time, as wallet gets more and more efficient this delay will most likely be able to be removed.

**Comment by chappjc** [comment]
@alexlyp Thanks for the feedback.  I'll have another commit tonight.

Regarding the t.Log(), it only displays with the `-v` flag passed to `go test`.  Still, it is a lot of extra unpolished logging statements, so I understand if removing them is still recommended.

**Comment by alexlyp** [comment]
Hrm that's true.  I suppose you could leave them if they offer clear information.  I did see some that just logged <nil>  I'm all for extra info, but you should drop ones that don't offer any new information to dev/users.

**Comment by chappjc** [comment]
@alexlyp PR updated.  Good to go.  There is room to improve the test approach of reusing a single harness for efficiency, but I will look at this going forward.

**Comment by alexlyp** [comment]
Great reviewing now.  Can you squash into 1 commit?  


git rebase master -i (pick the first one, s the rest)
Then you can erase all the other commit messages and just explain what this PR entails (eg. RFP10 milestone 1, rpctests A, B, C etc).  
git push chappjc rfp10-m1 --force

This just allows us to review more easily and makes sure that the git logs stay relatively tidy.  Thanks again.

**Comment by chappjc** [comment]
How about a squash merge?  If it's possible to keep the commit history in my branch, I would prefer that.

**Comment by alexlyp** [comment]
Ya nevermind that, it will get squashed anyways upon merge.

**Comment by jcvernaleo** [comment]
@chappjc and @alexlyp I have the github repos set to only allow squash merges, so the button should do what @alexlyp wants.

**Comment by alexlyp** [comment]
tACK and OK.  I'm going to clean up the merged commit message a bit as well.

**Pull request merged**
